//**    ids.h - resource ids

#define IDS_APP_TITLE             1

#define IDM_FILE_OPEN           201
#define IDM_FILE_PRINT		202
#define IDM_FILE_PRINTER_SETUP	203
#define IDM_FILE_EXIT		204

#define IDM_EDIT_COPY           251

#define IDM_OPTIONS_ORIGIN      301
#define IDM_OPTIONS_STATS	302

#define IDM_ABOUT               321


#define IDD_ABOUT               400


#define IDD_STATS               500
#define IDC_TITLE               503
#define IDC_FILE                505
#define IDC_DATE_FIRST          506
#define IDC_DAYS                507
#define IDC_DATE_LAST           508
#define IDC_SPLITS              512
#define IDC_SPLIT_FACTOR        514
#define IDC_LOW_OVERALL         520
#define IDC_HIGH_OVERALL        521
#define IDC_LOW_CLOSE           523
#define IDC_HIGH_CLOSE          524
